version = 1

exclude_patterns = [
  "apps/oxidize/src/prisma.rs",
  "apps/tnt/src/lib/locales/**"
]

[[analyzers]]
name = "rust"
enabled = true

[analyzers.meta]
msrv = "1.30.0"

[[analyzers]]
name = "javascript"
enabled = true
