[package]
name = "glowsquid"
version = "0.1.0"
description = "The glowsquid launcer"
authors = ["suyashtnt, redcreeper1485"]
license = "MIT"
repository = "https://github.com/glowsquid-launcher/glowsquid"
default-run = "glowsquid"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
copper = { version = "*", path = "../../copper" }
discord_api = "0.2.1"

[dependencies.tauri]
version = "1.0.0-beta"
features = ["api-all"]

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
